controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
app_front:
    path: /template
    controller: App\Controller\FrontController::index
